### ISSUE TITLE
What the difference between data/airbnb-{train|test}-indoor-filtered.tsv and data/bnb-dataset-*.tsv?

### ISSUE THREAD

**Issue by heyzude** [airbert-vln/bnb-dataset#10]
Hi,

Right after cloning this repo, there are `airbnb-test-indoor-filtered.tsv` and `airbnb-train-indoor-filtered.tsv` in `data` folder.
But after following README.md, `bnb-dataset-indoor.tsv`, `bnb-dataset-raw.tsv`, `bnb-dataset.tsv` and `noun_phrases.part-0-airbnb{train|test}.tsv`(I named these files myself. Originally named as `noun_phrases.part-0.tsv` for both) are created.

What's the difference btw `data/airbnb-{train|test}-indoor-filtered.tsv` and `data/bnb-dataset-*.tsv`?

I counted number of lines of some files. `airbnb-train-indoor-filtered.tsv` has 1565820 lines, `bnb-dataset-raw.tsv` has 1451945 lines.

Do they have common pictures? Are those filtered by indoor or not? Do they only have noun-filtered phrases?

**Comment by guhur** [comment]
The provided tsv files are after 2. And 3.
They can not be reproduced exactly since they depend on airbnb

**Comment by heyzude** [comment]
Oh I see. Thanks for the answer :)
