### ISSUE TITLE
number of the images in dataset

### ISSUE THREAD

**Issue by 1021331023** [airbert-vln/bnb-dataset#13]
I download the airbnb-test-indoor-filtered.tsv and airbnb-train-indoor-filtered.tsv，and find that the numbers of images are 118571 and 1523116 respectively, the sum of which is 1687452 and is not equal to “713K image-caption pairs and 676K images without captions” (13000+676000=1389000) in the paper. Could you explain this? Thanks.

**Comment by guhur** [comment]
The provided files are the output of the steps 2 and 3. Then when you try to download images, some of them are not downloadable. In the paper we reported the number of photos downloaded.

Please notice that this number is not reproducible, since airbnb listings have changed since Dec 2019.
