### ISSUE TITLE
some questions on README.md

### ISSUE THREAD

**Issue by 1021331023** [airbert-vln/bnb-dataset#14]
### :chains: 5.1. Concatenation

In this paper, concatenation means Concatenating Images and Texts in a BnB Listing,  it should exclude captionless images.

However, in "python preprocess_dataset.py --csv data/bnb-train.tsv --name bnb_train", parameter [--captionless] defaults to "True".

Should parameter [--captionless] be set "False" in this part?

### :busts_in_silhouette: 5.2. Image merging

"python merge_photos.py --source bnb_train.py --output merge+bnb_train.py --detection-dir data/places365 " has some errors.

Should [source] be set to "bnb_train.json" without captionless images or "2capt+bnb_train.json" with captionless images?

### 👣 5.4. Instruction rephrasing

In this part, I get "bnb-train.np.tsv" instead of "np+bnb_train.json" which is used in airbert training.

 Could you explain these? Thanks.

**Comment by guhur** [comment]
> Should parameter [--captionless] be set "False" in this part?
Yes. It depends on what you want to do.

> Should [source] be set to "bnb_train.json" without captionless images or "2capt+bnb_train.json" with captionless images?
Sure. It depends on what you want to do.

> In this part, I get "bnb-train.np.tsv" instead of "np+bnb_train.json" which is used in airbert training.
perturbate_dataset.py is exporting a JSON file.
