### ISSUE TITLE
Problem when getting start.

### ISSUE THREAD

**Issue by JeremyLinky** [airbert-vln/bnb-dataset#2]
When I followed your instructions "To parallelize among multiple GPUs, you can use the distributed.launcher script as is...", some problems occurred as follows:
![3da1628338715efa7eb527b97d1bcbc](https://user-images.githubusercontent.com/50053052/157161222-5c74d575-cfe4-42cc-a40a-cedc0de6b886.png)
And I found that this warning occurred at the beginning:
![image](https://user-images.githubusercontent.com/50053052/157161441-42acdd03-7886-4e0c-98ed-557b641425ce.png)

How can I fix this problem?

**Comment by guhur** [comment]
I just fixed this issue. However, I am keeping this issue opened, because workers should be launched with a torch Dataset (it would simplify a lot here).

**Comment by guhur** [comment]
In the end, I removed distributed computation from this file, since it takes just a couple of minutes to run.
