### ISSUE TITLE
TypeError: save_txt() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by JeremyLinky** [airbert-vln/bnb-dataset#3]
There are only 2 positional arguments in save_txt(), why do you input 3?
![image](https://user-images.githubusercontent.com/50053052/157168028-cf748757-68b3-4b5b-9e7c-34fbe36b97e0.png)

![image](https://user-images.githubusercontent.com/50053052/157168069-acfaa329-05ba-4df3-b1d2-fdaea5389596.png)

BTW, are you sure save_txt() saves any txt files? Because I only see the print operation there.

Thanks for your reply!

**Comment by guhur** [comment]
Hi, 
Sorry for the inconvenience.

What do you mean by: "BTW, are you sure save_txt() saves any txt files? Because I only see the print operation there."?
 
I fixed this issue, but I encounter another issue related to `allennlp`. I am keeping this issue open for now, I'll go back on this weekend.

**Comment by JeremyLinky** [comment]
> Hi, Sorry for the inconvenience.
> 
> What do you mean by: "BTW, are you sure save_txt() saves any txt files? Because I only see the print operation there."?
> 
> I fixed this issue, but I encounter another issue related to `allennlp`. I am keeping this issue open for now, I'll go back on this weekend.

thanks for your prompt reply! Could you also provide the versions of torch and python you are using?

**Comment by JeremyLinky** [comment]
Please let me know when you fix all the bugs in your project. Your work is awesome and I want to keep learning!

**Comment by guhur** [comment]
Great :) 
I was using python 3.6 and torch 1.7 at that time. But the code is one year old, and actually it makes time to update deps to python 3.9 and torch 1.10 now. I am also converting the codebase with `Makefile` and `poetry` to make it more usable.

**Comment by guhur** [comment]
I added further instructions of using `poetry` in the README. I hope it is gonna ease the install process :)
