### ISSUE TITLE
Where is the file 'data/bnb-test-indoor.tsv'?

### ISSUE THREAD

**Issue by JeremyLinky** [airbert-vln/bnb-dataset#5]
Where is the file 'data/bnb-test-indoor.tsv'?

**Comment by guhur** [comment]
Following the name convention, data/bnb-test-indoor.tsv means that this is the testset without filtering of captions, but with filtering of images. 

I am providing this file, but the following file is has both filtering of captions and images:

https://github.com/airbert-vln/bnb-dataset/blob/main/data/airbnb-test-indoor-filtered.tsv


If you need the file without filtering of captions, you should be able to re-generate it by collecting an bnb-dataset.tsv file, (see README.md step 2) and then filtering indoor images (step 3). Then splitting into train/test (step 4.1).

**Comment by JeremyLinky** [comment]
Thanks for your reply. Actually, I haven't figured it out yet: Can you explain the role of running the following instruction?
`python  -m torch.distributed.launch \
  --nproc_per_node=24 \
  --nnodes=1 \
  --node_rank=0 \
  -m extract_noun_phrases \
    --start 24 \
    --num_splits 48 \
    --source data/bnb-test-indoor.tsv \
    --output noun_phrases.tsv \
    --num_workers 8 \
    --batch_size 20`

Besides, there are some problems when I tried to download a list of listing from the list of cities as instruction:
`python search_listings.py --locations data/cities.txt --output data/listings`
 like `requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))` Haven't you fixed this script yet? 

I'm not very smooth in downloading bnb datasets, can you fix these bugs as soon as possible and then tell me then?

Thanks in advance!

**Comment by heyzude** [comment]
You have to fix `make_correspondance` function I think. 
After I fixed this part:
`
with open(args.locations, "r") as fid:
    locations = [l.strip() for l in fid.readlines()]
`
to something like this 
`
with open(args.locations, "r") as fid:
    locations = eval(fid.readlines()[0])
`
since data/cities.txt has list of locations in it, not in line-by-line form

**Comment by heyzude** [comment]
I'm facing some other bugs while trying to get the bnb data. I will post further issues when I finally download the dataset.
