### ISSUE TITLE
Error: unrecognized arguments: –local_rank=19

### ISSUE THREAD

**Issue by heyzude** [airbert-vln/bnb-dataset#6]
Hi, 
I have following error when I try to run 
`python  -m torch.distributed.launch \
  --nproc_per_node=24 \
  --nnodes=1 \
  --node_rank=0 \
  -m extract_noun_phrases \
    --start 24 \
    --num_splits 48 \
    --source data/bnb-test-indoor.tsv \
    --output noun_phrases.tsv \
    --num_workers 8 \
    --batch_size 20`
   
from README.md.
 `Error: unrecognized arguments: –local_rank=19`

A quick fix is here: https://discuss.pytorch.org/t/error-unrecognized-arguments-local-rank-1/83679

Could you please amend the extract_noun_phrases.py file?
And I also wonder why the file with same name is in the `scripts` folder too.

Thank you :)

**Comment by guhur** [comment]
Yeah nowadays, we should run `torchrun` instead of `torch.distributed.launch`. Anyways, distributed computation is not really useful for `extract_noun_phrases`: without any split, it takes ~5mn on my machine. So I removed it.
