### ISSUE TITLE
Error at 2.2. Download listings

### ISSUE THREAD

**Issue by heyzude** [airbert-vln/bnb-dataset#8]
As far as I know, `python search_listings.py --locations data/cities.txt --output data/listings` creates multiple listings.txt files at multiple different newly created folders.

So, the code in `python download_listings.py --listings data/listings.txt --output data/merlin` does not make sense and raises error.
(there is no `data/listings.txt` after executing `python search_listings.py --locations data/cities.txt --output data/listings`.)
I'm using os.walk to adjust `download_listings.py` code in order to get the json files

Is it what you intended to do that `python search_listings.py --locations data/cities.txt --output data/listings` creates multiple listings.txt files?

**Comment by guhur** [comment]
Hi @heyzude ,

Thanks for reporting this issue. I have fixed the output format  of `search_listings.py` such as `download_listings` works the intended way.
