### ISSUE TITLE
Way to get and use pool of ip addresses

### ISSUE THREAD

**Issue by heyzude** [airbert-vln/bnb-dataset#9]
As you mentioned in the README.md file, Airbnb server blocks my request after certain amount of consecutive requests. You mentioned utilizing pool of ip adresses. Could you also address how to get a pool of ip addresses, and how to use them?
I know some tricks to circumvent the TooManyRequest error, but I wonder what your method is.

**Comment by guhur** [comment]
I observed that Airbnb blocks flooding of requests. It might be so by measuring the number of requests per minute. So after each request, I left a timeout.

Some options exist for paying a pool of workers IP, but they aren't cheap.

In my case, I will ssh into a whole bunch of machines in my lab and download parts of listings from them. Downloading JSONs from Airbnb is really not CPU/IO intensive.
